import os

Import('env')

src_env = env.Clone()

src_env['srcs'] = []

src_env['srcs'] += Glob('HaeControllee/*.c')
src_env['srcs'] += Glob('interfaces/operation/*.c')

# Compile sources and create libraries
objs = src_env.StaticObject(src_env['srcs'])

lib = src_env.Library("ajtcl_hae", objs)
src_env.Install('#dist/lib', lib)

if src_env['build_shared']:
    objs = src_env.SharedObject(src_env['srcs'])
    lib = src_env.SharedLibrary("ajtcl_hae", objs)
    src_env.Install('#dist/lib', lib)
